#!/usr/bin/env ruby

require 'fog'
require 'colorize'

file = ARGV.first
dst  = File.join("validate-input", File.basename(file))

connection = Fog::Storage.new({
  :provider                 => 'AWS',
  :region                   => 'us-west-1',
  :aws_access_key_id        => ENV["AWS_ACCESS_KEY"],
  :aws_secret_access_key    => ENV["AWS_SECRET_KEY"]
})

directory = connection.directories.get("bioboxes-tools")
exists = directory.files.head(dst)

if exists
  STDERR.puts "Can't deploy, this version already exists: #{dst}".colorize(:red)
  exit 1
else
  directory.files.create(key: dst, body: File.open(file), public: true)
  STDOUT.puts "Successfully released #{dst}".colorize(:green)
end
