#!/usr/bin/env ruby

require 'fog'
require 'colorize'

file  = ARGV.first
patch_version = File.open(ARGV.last, 'r:iso-8859-1').read
minor_version = (patch_version.split('.')[0..1] << 'x').join('.')
major_version = (patch_version.split('.')[0..0] << 'x' << 'y').join('.')

patch = "validate-biobox-file/validate-biobox-file-#{patch_version}.tar.xz"
minor = "validate-biobox-file/validate-biobox-file-#{minor_version}.tar.xz"
major = "validate-biobox-file/validate-biobox-file-#{major_version}.tar.xz"

connection = Fog::Storage.new({
  :provider                 => 'AWS',
  :region                   => 'us-west-1',
  :aws_access_key_id        => ENV["AWS_ACCESS_KEY"],
  :aws_secret_access_key    => ENV["AWS_SECRET_KEY"]
})

directory = connection.directories.get("bioboxes-tools")
exists = directory.files.head(patch_version)

if exists
  STDERR.puts "Skipping deployment this version already exists: #{patch_version}".colorize(:red)
else
  directory.files.create(key: patch, body: File.open(file), public: true)
  STDOUT.puts "Successfully released #{patch_version}".colorize(:green)

  directory.files.create(key: minor, body: File.open(file), public: true)
  STDOUT.puts "Successfully updated #{minor}".colorize(:green)

  directory.files.create(key: major, body: File.open(file), public: true)
  STDOUT.puts "Successfully updated #{major}".colorize(:green)
end
