#!/bin/bash

hash fswatch 2>/dev/null || {
  echo >&2 'Need `fswatch` to be installed to start automatic tests'
  exit 1
}

CMD='clear && ./script/test'
eval ${CMD}
fswatch -o ./validate_input -o ./test | xargs -n 1 -I {} bash -c "eval ${CMD}"
