#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

SRC=/src/validate-biobox-file.tar.xz

TOOL_VERSION=${1}
DEB_VERSION=${2}
NAME=$(basename ${SRC} .tar.xz)

DEB=${NAME}_${TOOL_VERSION}_${DEB_VERSION}

cd $(mktemp -d)
tar -xJf ${SRC}

mkdir -p ${DEB}/DEBIAN ${DEB}/usr/bin
cp build/${NAME} ${DEB}/usr/bin

cat << EOF > ${DEB}/DEBIAN/control
Package: ${NAME}
Version: $(cat build/VERSION)
Architecture: all
Maintainer: Michael Barton<mail@michaelbarton.me.uk>
Installed-Size: 2
Depends:
Section: extras
Priority: optional
Homepage: http://bioboxes.org/validate-biobox-file/
Description: A tool for validating biobox.yaml files.
EOF

dpkg --build ${DEB}
cp ${DEB}.deb $(dirname ${SRC})
